config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/amenidades', to: 'pages#amenidades'
  get '/contatos', to: 'pages#contatos'
  get '/eventos', to: 'pages#eventos'
  get '/quartos', to: 'pages#quartos'
  get '/sobrenos', to: 'pages#sobrenos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HOTELOK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/amenidades.html.erb
<div class="card-category">
    AMENIDADES E SERVIÇOS
</div>

<div class="container">
    <div class="row">
        <div class="column">
            <%= image_tag "piscina.jpg", class: "image-index" %>
        </div>
        <div class="column">
            <%= image_tag "cafe.jpg", class: "image-index" %>
           
        </div>
        <div class="column">
            <%= image_tag "academia.jpg", class: "image-index" %>
        </div>

        <div class="column">
            <div class="card-white">
                <p>
                    Piscina em terraço amplo
                    <br>
                    Academia
                    <br>
                    Wi-Fi gratuito
                    <br>
                    Salas de eventos
                    <br>
                    Cafeteria no térreo
                    <br>
                    Ponto de táxi em frente ao hotel
                    <br>
                    Café da manhã com buffet
                </p>
            </div>
        </div>
    </div>
</div>

app/views/pages/contatos.html.erb
<div class="card-category">
    CONTATO
</div>

app/views/pages/eventos.html.erb
<div class="card-category">
    EVENTOS
</div>
<div class="container">
    <div class="row">
        <div class="column">
            <%= image_tag "eventos.jpg", class: "image-index" %>           
        </div>

        <div class="column">
            <p class="card-white">
                O Hotel OK possui três salas para convenções e eventos empresariais.
                <br><br>
                Sala Búzios - 52m²
                <br>
                Sala Paraty - 60m²
                <br>
                Sala Saint Tropez - 70m²
        
            </p>        
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="5000">
        <div class="carousel-inner">
            <div class="carousel-item active">
            <%= image_tag "entrada2.jpg", class: "d-block w-100" %>
            </div>
            <div class="carousel-item">
            <%= image_tag "entrada.jpg", class: "d-block w-100" %>
            </div>
            <div class="carousel-item">
            <%= image_tag "saguao.jpg", class: "d-block w-100" %>
            </div>
        </div>
    </div>
</div>

app/views/pages/quartos.html.erb
<div class="card-category">
    Quartos
</div>
<div class="container">
    <div class="row">
        <div class="column">
            <%= image_tag "quarto.jpg", class: "image-index" %>
            <p class="card-white">Nossos quartos contam com televisão, Wi-Fi, ar-condicionado, banheiro, frigobar, cofre e secador.

Temos variadas opções de quartos, com camas de casal e de solteiro (duplas ou triplas), além de quartos especiais para pessoas com mobilidade reduzida. Consulte nossa disponibilidade.</p>
        </div>

        <div class="column">
            <%= image_tag "quarto2.jpg", class: "image-index" %>
        </div>

        <div class="column">
            <%= image_tag "quarto3.jpg", class: "image-index" %>
        </div>

        <div class="column">
            <%= image_tag "banheiro.jpg", class: "image-index" %>
            <%= image_tag "banheiro2.jpg", class: "image-index" %>
        </div>
    </div>
</div>

app/views/pages/sobrenos.html.erb
<div class="card-category">
    SUA TRADICIONAL OPÇÃO NO CENTRO DO RIO
</div>
<div class="container">
    <div class="row">
        <div class="column">
            
            <%= image_tag "terreo.jpg", class: "image-index" %>
            <%= image_tag "fachada.jpg", class: "image-index" %>
        </div>
        <div class="column">
            <%= image_tag "vista.jpg", class: "image-index" %>
            <%= image_tag "vistanoite.jpg", class: "image-index" %>
        </div>
        <div class="column">
            <%= image_tag "salao2.jpg", class: "image-index" %>
            <%= image_tag "salao.jpg", class: "image-index" %>
        </div>
        <div class="column">
            <%= image_tag "vistanoite2.jpg", class: "image-index" %>
            <p class="card-white">Fundado em 1949, o Hotel OK é um dos mais tradicionais do Rio de Janeiro. Bem localizado no Centro da cidade, se situa próximo à Lapa – tradicional reduto da boemia carioca – e ao lado da estação de metrô da Cinelândia. Também apresenta fácil acesso à Zona Sul e ao aeroporto Santos Dumont.</p>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <h5>Rua Senador Dantas, nº 24
Centro, Rio de Janeiro/RJ 20031-203  |

+55(21) 3226-5151</h3>
  <div class="footer-links">
    <a href="https://www.instagram.com/hotelokrj/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/hoteisok" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto inline">
      
      <li class="nav-item">
        <%= link_to "Sobre Nós", sobrenos_path,  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Quartos", quartos_path,  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Amenidades", amenidades_path,  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Eventos", eventos_path,  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contato", contatos_path,  class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>